name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiY2Y2ZGY3N2YtZTRkNC00NzVkLTkzNmYtN2U2YWY2M2JmYjYyIiwidGVuYW50X2lkIjoiNTRmMjg3YzgzMDliNWI1MWQ4NWM4NWNjNTg3NGY4MzVhZjQ0ODRkYWRiMDY5MzZmZDUzYTFhNzFlZDI5YWIxOCIsImludGVybmFsX3NlY3JldCI6IjlmZWNkZjg5LTczMDgtNDMyZi1iYWM1LThkYmM2Nzc0NDg1YyJ9.ZOD4sA10iHCwiY7tJvcL4doL67N09n-0XsB6RDjXXfg"